//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppVendas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendas
    {
        public int Id { get; set; }
        public string Produto { get; set; }
        public string Descricao { get; set; }
        public Nullable<System.DateTime> DataVenda { get; set; }
        public Nullable<decimal> Valor { get; set; }
    }
}
